name: shotcaller
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.4+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.6
  firebase_storage: ^8.0.0
  firebase_core:
  firebase_messaging:
  country_code_picker: ^2.0.1
  image_cropper: ^1.3.1
  image_picker:
  cached_network_image: ^2.5.1
  get: ^3.24.0
  permission_handler:
  agora_rtc_engine: ^3.2.1
  firebase_dynamic_links: ^0.5.0+11
  flutter_local_notifications:
  http: ^0.13.0
  flutter_svg:
  vibration: ^1.7.3
  audioplayers: ^0.19.1
  video_player:
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sounds/seconds_added.mp3
    - assets/sounds/hangup.mp3
    - assets/sounds/seconds_addedc.mp3
    - assets/sounds/economics.mp3
    - assets/images/
    - assets/videos/
  fonts:

    - family: RobotoMedium
      fonts:
        - asset: fonts/Roboto-Medium.ttf

    - family: RobotoRegular
      fonts:
        - asset: fonts/Roboto-Regular.ttf

    - family: RobotoBold
      fonts:
        - asset: fonts/Roboto-Bold.ttf

    - family: InterThin
      fonts:
        - asset: fonts/InterThin.ttf

    - family: InterExtraLight
      fonts:
        - asset: fonts/Inter-ExtraLight.ttf

    - family: InterLight
      fonts:
        - asset: fonts/Inter-Light.ttf

    - family: InterExtraBold
      fonts:
        - asset: fonts/Inter-ExtraBold.ttf

    - family: InterBold
      fonts:
        - asset: fonts/Inter-Bold.ttf

    - family: InterSemiBold
      fonts:
        - asset: fonts/Inter-SemiBold.ttf

    - family: InterRegular
      fonts:
        - asset: fonts/Inter-Regular.ttf

    - family: InterMedium
      fonts:
        - asset: fonts/Inter-Medium.ttf

    - family: RobotoLight
      fonts:
        - asset: fonts/Roboto-Light.ttf
